apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieswiper-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieswiper
  template:
    metadata:
      labels:
        app: movieswiper
    spec:
      containers:
        - name: movieswiper
          image: bodzioss/movieswiper:latest