apiVersion: v1
kind: Service
metadata:
  name: movieswiper-srv
spec:
  type: NodePort
  selector:
    app: movieswiper
  ports:
    - name: movieswiper
      protocol: TCP
      port: 8080
      targetPort: 8080